### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by liao961120** [github-classroom-test-2019/Note#1]
- [x] Make sure **private repo** is available
- [x] Automate email notifications when issues is raised and commented in student's repo (See #2)
- [x] Automate hw deadLines and push latest HW to `branch: gh-pages` (See [this python script](https://github.com/liao961120/2019-Rcourse/blob/master/create-gh-pages-for-hw.py))
